[general]
    name = "Hexoskin"
    nameRegex = "HX-(\\d)+"
    type = "Vest"
    characteristicNames = ["heartRate", "batteryInfo"]
[heartRate]
    name = "Heart Rate"
    serviceUUID = "0000180d-0000-1000-8000-00805f9b34fb"
    characteristicUUID = "00002a37-0000-1000-8000-00805f9b34fb"
#   formula = ""
[respirationRate]
    name = "Respiration Rate"
    serviceUUID = "3b55c581-bc19-48f0-bd8c-b522796f8e24"
    characteristicUUID = "9bc730c3-8cc0-4d87-85bc-573d6304403c"
#   formula = ""
[accelerometerRate]
    name = "Accelerometer Rate"
    serviceUUID = "bdc750c7-2649-4fa8-abe8-fbf25038cda3"
    characteristicUUID = "75246a26-237a-4863-aca6-09b639344f43"
#   formula = ""
